Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/10/2024
Var
testeSimples : inteiro
nomes : vetor[1..3] de caractere

Inicio
testeSimples <- 3
testeSimples <- 5

nomes[2] <- "Laura"
nomes[3] <- "Alessandro"
nomes[1] <- "Bruna"

leia(nomes[2])

para i de 1 ate 3 faca
 escreval(nomes[i])
fimPara
Fimalgoritmo